title = "HOME"
baseURL = "https://www.envirosafepe.com"
languageCode = "en-us"
theme = "ananke"
featured_image = "/images/dawn2.jpg"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 50 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-18099858-1"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/images/Leaf1.png"
  site_logo = "/images/enviroleaf1.jpeg"
  description = "Cleaning the environment as nature intended."
  facebook = "https://www.facebook.com/vince.hall.5268750"
  instagram = ""
  youtube = ""
  github = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-green"
  featured_image = "/images/dawn2.jpg"
  recent_posts_number = 16
